name: upload
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: build
        run: |
          npm install
          npx @11ty/eleventy
      - name: install awscli
        run: |
          sudo apt update
          sudo apt install -y awscli
      - name: upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --acl public-read \
            --region us-east-1 \
            ./_site/ s3://juancri-web
      - name: invalidate cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E37VQK4W6O1P5V \
            --paths '/*'
