name: upload
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: install dependencies
        run: npm install
      - name: build
        run: npx @11ty/eleventy
      - name: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          arch: amd64
      - name: upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --acl public-read \
            --region us-east-1 \
            ./_site/ s3://juancri-web
      - name: invalidate cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E37VQK4W6O1P5V \
            --paths '/*'
